fixed description in tests
oaplatform/oap-ws pull request #143
Opened 2023-11-22 13:09 UTC by JuliaGalabut

2023-11-22 13:11 UTC, BorisTkachenko approved these changes

2023-11-22 14:32 UTC, alebastrov submitted a review, later dismissed

2023-11-28 15:11 UTC, alebastrov requested changes

2023-11-28 15:11 UTC, alebastrov commented on oap-ws-account-api/src/main/java/oap/ws/account/UserData.java
> +        return Optional.ofNullable( user.defaultOrganization ).or( Optional::empty );
do not need .or( Optional::empty )

2023-11-28 15:11 UTC, alebastrov commented on oap-ws-account-api/src/main/java/oap/ws/account/UserData.java
> +        return Optional.ofNullable( user.defaultAccounts.get( organizationId ) ).or( Optional::empty );
same

2023-11-28 15:17 UTC, JuliaGalabut commented on oap-ws-account-api/src/main/java/oap/ws/account/UserData.java
> +        return Optional.ofNullable( user.defaultOrganization ).or( Optional::empty );
+

2023-11-28 15:17 UTC, JuliaGalabut commented on oap-ws-account-api/src/main/java/oap/ws/account/UserData.java
> +        return Optional.ofNullable( user.defaultAccounts.get( organizationId ) ).or( Optional::empty );
removed

2023-11-28 15:17 UTC, JuliaGalabut commented on oap-ws-account-api/src/main/java/oap/ws/account/UserData.java
> +        if( !user.defaultAccounts.containsKey( organizationId ) ) {
changed

2023-11-28 15:19 UTC, alebastrov submitted a review, later dismissed

2023-11-29 08:06 UTC, alebastrov approved these changes

2023-11-29 08:06 UTC, merged