PLAT-65: Fix for circular referencing in API introspection
oaplatform/oap-ws pull request #36
Opened 2022-09-12 14:08 UTC by jcuk

Fixes an issue where any circular reference in any object returned by a web service method breaks the recursive walk of the  web service api in `/system/api` functionality with an infinite loop and stack overflow error. The fix checks if any object has been rendered as part of the object tree before. If it has, then the rendering for that branch is terminated with a message `Recursive Reference`.

2022-09-12 15:58 UTC, vdiravka approved these changes
+1 LGTM

2022-09-12 17:28 UTC, vovakyrychenko approved these changes

2022-09-12 17:29 UTC, vovakyrychenko requested changes
pom.xml version bump

2022-09-13 17:16 UTC, jcuk commented
> pom.xml version bump

@vovakyrychenko oap-ws.project.version changed from 17.11.3.2 -> 17.11.3.3

2022-09-16 10:59 UTC, merged